### ISSUE TITLE
PVP Display Issue

### ISSUE THREAD

**Issue by sketchysocks** [WatWowMap/DataParser#35]
![PVP-Issue](https://user-images.githubusercontent.com/58572875/93495486-2a09cb80-f8dc-11ea-9c06-c33e81b7e411.png)

Same version of MapJS (1.6.4) for both. RDM on the left, DP on the right. 

- IVs not displayed
- Incorrect Rank
- Incorrect %
- Some pvp spawns don't have any stats in the pop up but still show up when filtered
- Pvp filter only returns ~half as many results as the same pvp filter on rdm db.

**Comment by versx** [comment]
Interesting I don't think I've seen it not show the IV's row, someone had mentioned there was an issue that only some of the individual values would be saved at times so maybe that has something to do with that.
I know the percentage format is off because RDM saves it as `0.9972` while DP saves as `99.72` so MapJS is multiplying 99.72 * 100 to get the 9999%. I'll change the pvp script to match RDM's style for compatibility.
The pvp filtering issue might be because DP can save Great, Ultra, or both stats while RDM only does both or none. (If that makes sense) So some filtering might need to be adjusted tbh.

For example, run this query against both databases pokemon table, RDM shouldn't return anything but DP should:
```sql
SELECT * FROM pokemon WHERE expire_timestamp > UNIX_TIMESTAMP() AND 
(
    pvp_rankings_great_league IS NULL AND
    pvp_rankings_ultra_league IS NOT NULL
);
```
